### ISSUE TITLE
error when go install v1.11.0

### ISSUE THREAD

**Issue by frankful** [gotestyourself/gotestsum#372] opened 2023-09-27 08:10 UTC
$ go install gotest.tools/gotestsum@latest
go: downloading gotest.tools/gotestsum v1.11.0
go: downloading gotest.tools v1.4.0
go: downloading gotest.tools v2.2.0+incompatible
go: downloading github.com/dnephin/pflag v1.0.7
go: downloading github.com/fatih/color v1.15.0
go: downloading golang.org/x/tools v0.11.0
go: downloading github.com/google/shlex v0.0.0-20191202100[45](http://10.0.0.10/git.multiverse.io/statusmgmt/monitor/-/jobs/1122179#L45)8-e7afc7fbc510
go: downloading github.com/bitfield/gotestdox v0.2.1
go: downloading golang.org/x/sync v0.3.0
go: downloading golang.org/x/term v0.10.0
go: downloading github.com/fsnotify/fsnotify v1.5.4
go: downloading golang.org/x/sys v0.10.0
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.19
go: downloading golang.org/x/text v0.11.0
go: downloading golang.org/x/mod v0.12.0
.go/pkg/mod/gotest.tools/gotestsum@v1.11.0/testjson/format.go:11:2: //go:build comment without // +build comment

**Comment by frankful** [comment] 2023-09-28 08:25
kubernetes 1.20 gitlab runner, ubutun 18.04, golang 1.17.9

**Comment by dnephin** [comment] 2023-09-29 02:12
I tried this and it installed properly without any errors. 

```
$ docker run -ti golang:1.17.9 go install gotest.tools/gotestsum@latest
```


It sounds like the error is described in this issue: https://github.com/golang/go/issues/51436

And this does reproduce it:

```
$ docker run -ti golang:1.16.9 go install gotest.tools/gotestsum@latest
```

Both Go1.16 and Go1.17 are past their EOL. The only supported Go versions are 1.21 and 1.20. I think the fix is to upgrade your version of Go.

**Comment by dnephin** [comment] 2024-05-30 03:45
Going to close this issue since I was not able to reproduce it.

**Closed by dnephin** 2024-05-30 03:45 UTC
Labels: question
