### ISSUE TITLE
junit.xml incorrect PASS testcase

### ISSUE THREAD

**Issue by ShiinaOrez** [gotestyourself/gotestsum#109] opened 2020-05-11 10:23 UTC
I'm writing a CI project, but when I use **gotestsum** to sum how many testcase success or failed, I found the PASS testcase number is **1 less than** actual PASS testcase.
But failures is correct, it's so weird.

my command is :
`gotestsum --format short-verbose --junitfile junit.xml -- -gcflags "all=-N -l" ./tests -coverprofile=coverage.out -coverpkg=./MYPACKAGE ./MYPACKAGETOO -covermode=count`

the junit.xml generated by auto:
```
<testsuites>
	<testsuite tests="31" failures="0" time="48.320000" name="MYCLASSNAME">
		<properties>
			<property name="go.version" value="go1.12.1 linux/amd64"></property>
		</properties>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="0.150000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="7.960000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.840000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="0.090000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.040000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.110000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="0.910000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.000000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="0.900000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.020000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="0.930000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.080000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.100000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.280000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.050000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.220000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.060000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="0.140000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="3.240000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="2.150000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="3.080000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="2.970000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="0.220000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="3.060000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="0.180000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.240000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="1.240000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="0.150000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="2.350000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="4.500000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="0.000000"></testcase>
		<testcase classname="MYCLASSNAME" name="MYTESTCASENAME" time="0.060000"></testcase>
	</testsuite>
</testsuites>
```

U will see the number of `tests` is not equal with real testcases number.

**Comment by ShiinaOrez** [comment] 2020-05-11 12:17
News:
I found the reason caused this issue: if you want use gotestsum in .sh file, NOT sign `set -ex` at first, it will make the result - 1.

```sh
set -ex
gotestsum --format short-verbose -junitfile junit.xml
```

the result will 1 LESS than REAL result.

**Comment by dnephin** [comment] 2020-05-16 19:58
Thank you for the bug report! I haven't seen this problem before and I'm not sure what might cause it.

What does the summary line (`DONE x tests, ...`) say? Does that have 31 or 32?

**Comment by dnephin** [comment] 2020-05-16 20:02
One way this could happen is if the package fails despite no failed test cases. In that case an extra failed `<testcase>` will be added with a name of `TestMain`, so that those failures are visible from the junit xml. Do you see that in the output?

**Comment by ShiinaOrez** [comment] 2020-05-18 06:27
> Thank you for the bug report! I haven't seen this problem before and I'm not sure what might cause it.
> 
> What does the summary line (`DONE x tests, ...`) say? Does that have 31 or 32?

DONE 31 tests, incorrect too.

**Comment by ShiinaOrez** [comment] 2020-05-18 06:30
> One way this could happen is if the package fails despite no failed test cases. In that case an extra failed `<testcase>` will be added with a name of `TestMain`, so that those failures are visible from the junit xml. Do you see that in the output?

I have tried a lot of situation, ALL PASS, or just ONE FAIL, or TWO FAIL... and more, but result never change, PASS count 1 less than the real situation.

**Comment by ShiinaOrez** [comment] 2020-05-18 06:33
For now, just ONE situation I got the right count:

Cause I run `gotestsum` in shell script to build CI pipeline at Jenkins, I have to set `set -ex` at the script file, but when if I delete it, the PASS count be right. It's strange, and Non-reproducible.

**Comment by dnephin** [comment] 2022-08-06 18:16
Since we were not able to reproduce this problem, and it has been a couple years, I'm going to close this issue.

If you are still experiencing the problem, please comment and I can try to help reproduce.

**Closed by dnephin** 2022-08-06 18:16 UTC
Labels: bug
