### ISSUE TITLE
Using gotest binary in jenkins pipeline

### ISSUE THREAD

**Issue by manikesh** [gotestyourself/gotestsum#54] opened 2019-05-06 11:48 UTC
I am using gotestum  unix binary in my jenkins pipleline, issue is when it starts running tests  it looks for some libs related to gotestsum, since libs are not available it fails. my concern is when binary is used it should not look for required libs, we are not building the code of gotestsum, we are just using the binary. 

when same is run on local IDE, it does not look for libs, it just runs test and shared result, same is expected in pipeline as well but it fails.

Only diff is on local we use, exe and in jenkins it uses linux binary.

**Comment by dnephin** [comment] 2019-05-06 16:56
Duplicate of #55

**Closed by dnephin** 2019-05-06 16:56 UTC
