### ISSUE TITLE
Undefined libraries when running go get github.com/gotestyourself/gotestsum

### ISSUE THREAD

**Issue by imsebasbo** [gotestyourself/gotestsum#162] opened 2020-11-12 00:54 UTC
I'm creating a test pipeline using docker with the following image:
`golang:1.12-stretch`
One of the commands is 
`go get github.com/gotestyourself/gotestsum`
but when the command runs I'm getting the following error:

```
# vendor/gotest.tools/gotestsum/internal/filewatcher
/go/src/vendor/gotest.tools/gotestsum/internal/filewatcher/term_unix.go:16:15: undefined: unix.IoctlGetTermios
/go/src/vendor/gotest.tools/gotestsum/internal/filewatcher/term_unix.go:23:13: undefined: unix.IoctlSetTermios
/go/src/vendor/gotest.tools/gotestsum/internal/filewatcher/term_unix.go:31:12: undefined: unix.IoctlSetTermios
```

**Comment by dnephin** [comment] 2020-11-12 01:04
Hmm, I just tried this out myself, it seems to work for me:

```
$ docker run --rm -ti golang:1.12-stretch bash
Unable to find image 'golang:1.12-stretch' locally
1.12-stretch: Pulling from library/golang
3192219afd04: Pull complete 
17c160265e75: Pull complete 
cc4fe40d0e61: Pull complete 
9d647f502a07: Pull complete 
c1f80dacfc85: Pull complete 
96df59423a0b: Pull complete 
7566c54d132a: Pull complete 
Digest: sha256:8b0f4fee390ca1308ef5c522accad9f7d98a4134fcde1b2cff33df1cbb1b3b97
Status: Downloaded newer image for golang:1.12-stretch
root@e7b5f514cceb:/go# go version
go version go1.12.17 linux/amd64
root@e7b5f514cceb:/go# gotestsum --version
gotestsum version dev
```

Those imports are a recent change on master, but I thought they had been in `golang/x/sys/unix` for a while.

Maybe there is a very old version of the `golang/x/sys/unix` package that isn't being updated? You could try `go get -u` to have it updated, or installing a binary from https://github.com/gotestyourself/gotestsum/releases

#131 is a similar report of problems with `go get`, but I was never able to reproduce.

Another option is to try enabling module mode with this:

```
$ export GO111MODULE=on
$ go get gotest.tools/gotestsum
```

**Comment by dnephin** [comment] 2020-11-12 01:07
Are you running on linux or some other OS? The `x/sys` libraries are OS-specific, so if you are on something else maybe I got the build tags wrong. The CI pipeline only tests linux, darwin and windows.

**Comment by imsebasbo** [comment] 2020-11-12 21:05
Hi @dnephin . I'm using linux. As mentioned I'm using bitbucket's pipelines in which I'm using `golang:1.12-stretch`. Until last week it was working fine, we hadn't done any modifications to the pipeline and suddenly it stop working this week.

I tried different images but the results are the same. From your suggestions:

- Getting again `golang/x/sys/unix` : 🚫  did not work
- Enabling module work export `GO111MODULE=on` :  🚫 did not work, I'm getting the following error:
```
go get -u github.com/gotestyourself/gotestsum
go: finding github.com/gotestyourself/gotestsum v0.6.0
go: github.com/gotestyourself/gotestsum@v0.6.0: parsing go.mod: unexpected module path "gotest.tools/gotestsum"
go get: error loading module requirements
```
- Downloading the binary directly : ✅  it worked.

**Comment by dnephin** [comment] 2020-11-12 21:55
With `GO111MODULE=on` I think you'll need to use `go get gotest.tools/gotestsum` which is the module path. The module has a different VCS url, which only works with modules turned off.

I guess the reason it stopped working is because I merged a PR which added those imports. But I'm still not sure why it can't find them if `x/sys/unix` is updated.

**Comment by dnephin** [comment] 2021-03-27 17:55
Looking at this issue again, it seems like the problem was the module path being used. `go get gotest.tools/gotestsum` works, but using the github url does not. I think that is expected because the module name is `gotest.tools/gotestsum.

**Closed by dnephin** 2021-03-27 17:55 UTC
Labels: question
